"use strict";

// Merges tools/sources.json into CalendarData.js. Run after changing either.
//
//   node tools/build-table.js          rewrite CalendarData.js
//   node tools/build-table.js --check  fail if CalendarData.js is stale

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const OUTPUT = path.join(ROOT, "CalendarData.js");

const FIRST_YEAR = 2000;
const LAST_YEAR = 2090;

// Both kept projecting past the last patro year, so they lose their vote past it.
const STALE_PAST_PATRO = ["sharing", "medic"];

// The last BS year the Panchanga Nirnayak Samiti has published.
const PUBLISHED_THROUGH = 2083;

// Ties are resolved by name and reason, never by read order.
const TIE_BREAKS = {
  2084: {
    winner: "amitgaru",
    reason: "hamropatro.com agrees with amitgaru and django for all 12 months; ashok has 366",
  },
};

function loadSources() {
  const blob = JSON.parse(fs.readFileSync(path.join(__dirname, "sources.json"), "utf8"));
  const ground = {};
  const libraries = {};
  for (const [name, entry] of Object.entries(blob.sources)) {
    const target = entry.groundTruth ? ground : libraries;
    target[name] = entry.monthLengths;
  }
  return { ground, libraries, meta: blob.sources };
}

function tally(tables, year, eligible) {
  const votes = new Map();
  for (const name of eligible) {
    const lengths = tables[name][year];
    if (!lengths) continue;
    const key = lengths.join(",");
    if (!votes.has(key)) votes.set(key, { lengths, holders: [] });
    votes.get(key).holders.push(name);
  }
  return [...votes.values()].sort((a, b) => b.holders.length - a.holders.length);
}

// Ground truth wins once two libraries corroborate it, otherwise they outvote it.
function decide(ground, libraries, year) {
  const patro = ground.patro[year];
  const eligible = Object.keys(libraries).filter(
    (name) => patro || !STALE_PAST_PATRO.includes(name)
  );
  const ranked = tally(libraries, year, eligible);

  if (patro) {
    const corroboration = ranked.find((vote) => vote.lengths.join(",") === patro.join(","));
    if (corroboration && corroboration.holders.length >= 2) {
      return { lengths: patro, tier: "attested", holders: ["patro", ...corroboration.holders] };
    }
    return { lengths: ranked[0].lengths, tier: "attested", holders: ranked[0].holders };
  }

  const winner = resolve(ranked, year);
  return {
    lengths: winner.lengths,
    tier: year <= PUBLISHED_THROUGH ? "published" : "provisional",
    holders: winner.holders,
  };
}

function resolve(ranked, year) {
  if (ranked.length < 2 || ranked[0].holders.length > ranked[1].holders.length) return ranked[0];

  const rule = TIE_BREAKS[year];
  const winner = rule && ranked.find((vote) => vote.holders.includes(rule.winner));
  if (!winner) {
    const split = ranked.map((vote) => vote.holders.join("+")).join(" vs ");
    throw new Error(`${year}: no majority (${split}); add a TIE_BREAKS entry`);
  }
  return winner;
}

function validate(rows) {
  for (const { year, lengths } of rows) {
    if (lengths.length !== 12) throw new Error(`${year}: ${lengths.length} months`);
    for (const days of lengths) {
      if (days < 29 || days > 32) throw new Error(`${year}: month of ${days} days`);
    }
    const total = lengths.reduce((a, b) => a + b, 0);
    if (total !== 365 && total !== 366) throw new Error(`${year}: ${total} days`);
  }
}

function render(rows, meta) {
  const credits = Object.entries(meta)
    .map(([name, entry]) => `//   ${name.padEnd(9)} ${entry.repository} (${entry.license})`)
    .join("\n");

  const table = rows
    .map(({ year, lengths, tier }) => {
      const total = lengths.reduce((a, b) => a + b, 0);
      const cells = lengths.map((days) => String(days).padStart(2)).join(", ");
      return `  [${cells}], // ${year}  ${total}  ${tier}`;
    })
    .join("\n");

  return `.pragma library

// Generated by tools/build-table.js. Do not edit by hand.
//
// Bikram Sambat month lengths are fixed by the moment the sun crosses into each
// zodiac sign, so they are published rather than derived. Merged from:
${credits}
//
// attested    confirmed day by day against a published patro
// published   past the patro but inside what the Samiti has published
// provisional nobody has determined these years yet

var FIRST_YEAR = ${FIRST_YEAR}
var LAST_YEAR = ${LAST_YEAR}
var ATTESTED_THROUGH = ${rows.filter((r) => r.tier === "attested").at(-1).year}
var PUBLISHED_THROUGH = ${PUBLISHED_THROUGH}

// 1 Baisakh ${FIRST_YEAR} BS.
var ANCHOR_AD = { year: 1943, month: 4, day: 14 }

var MONTH_LENGTHS = [
${table}
]
`;
}

function main() {
  const { ground, libraries, meta } = loadSources();
  const rows = [];
  for (let year = FIRST_YEAR; year <= LAST_YEAR; year += 1) {
    rows.push({ year, ...decide(ground, libraries, year) });
  }
  validate(rows);

  const rendered = render(rows, meta);
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, "utf8") : "";
    if (current !== rendered) {
      console.error("CalendarData.js is stale; run: node tools/build-table.js");
      process.exit(1);
    }
    console.log("CalendarData.js is up to date");
    return;
  }

  fs.writeFileSync(OUTPUT, rendered);
  const counts = rows.reduce((acc, row) => ({ ...acc, [row.tier]: (acc[row.tier] || 0) + 1 }), {});
  console.log(`wrote ${path.relative(ROOT, OUTPUT)}: ${rows.length} years`);
  for (const [tier, count] of Object.entries(counts)) console.log(`  ${tier.padEnd(12)} ${count}`);
}

main();
